services: 
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file:
      - ./nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
  
  travel-backend:
    container_name: travel_backend
    build:
      context: ./backend
    # image: rhinoman/travel-backend
    # ports:
    #   - "5003:5003"

  travel-frontend:
    container_name: travel_frontend
    build:
      context: ./frontend
    # image: rhinoman/travel-frontend
    # ports:
    #   - "3003:80"

volumes:
  nginx_secrets: